[package]
authors = ["Arvid Norlander"]
categories = ["config"]
description = "Library to merge ini files subject to configuration."
edition = "2021"
keywords = ["ini", "config", "configuration", "merge"]
license = "LGPL-3.0-only"
name = "ini-merge"
repository = "https://github.com/VorpalBlade/ini-merge"
rust-version = "1.70.0"
version = "0.3.5"

[dependencies]
ini-roundtrip = "0.1.2"
itertools = { version = "0.12.0", default-features = false }
keyring = { version = "2.3.1", optional = true, default-features = false, features = [
    "linux-secret-service",
    "platform-freebsd",
    "platform-windows",
    "platform-macos",
] }
lending-iterator = { version = "0.1.7", default-features = false }
log = { version = "0.4.20", default-features = false }
ouroboros = { version = "0.18.2", default-features = false }
regex = "1.10.2"
thiserror = { version = "1.0.56", default-features = false }

[dev-dependencies]
indoc = "2.0.4"
pretty_assertions = { version = "1.4.0", default-features = false, features = [
    "std",
] }
