[package]
authors = ["Arvid Norlander"]
categories = ["config"]
description = "Library to merge ini files subject to configuration."
edition = "2021"
keywords = ["ini", "config", "configuration", "merge"]
license = "LGPL-3.0-only"
name = "ini-merge"
repository = "https://github.com/VorpalBlade/ini-merge"
version = "0.1.1"

[dependencies]
ini-roundtrip = "0.1.2"
itertools = "0.10.5"
keyring = { version = "2.0.3", optional = true }
lending-iterator = { version = "0.1.7", default-features = false }
ouroboros = "0.17.0"
regex = "1.8.4"
thiserror = "1.0.40"

[dev-dependencies]
indoc = "2.0.1"
pretty_assertions = "1.3.0"
